<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/BusinessAdmin.Master" AutoEventWireup="true" CodeBehind="ConfigSupplementsPoints.aspx.cs" Inherits="e_Travel.BusinessAdmin.ConfigSupplementsPoints" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<link href="../Scripts/JqueyUI/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="../Scripts/JqueyUI/jquery-ui.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $(document).tooltip();
        });
    
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="FromBody">
        <asp:UpdatePanel runat="server" ID="UpdatePanel1">
            <ContentTemplate>
                <div class="BoxHeader">
                   Supplements Points Configuration</div>
                <div class="BoxBody">
                    <div class="BoxContent">
                    
                    <div style="clear:both;"></div>
                    
                        <fieldset style="float: left; margin-right: 15px; overflow: auto; width: 515px;">
                            <legend>Select Itinerary to Configure Supplement Points</legend>
                            <div>
                                 <searchGridUC:SearchCustomGridView ID="ItinerarySearchCustomGridView" runat="server"  />
                            </div>
                        </fieldset>
                        
                        <fieldset style="float: left; margin-right: 5px; overflow: hidden; width: 350px; height: 440px;">
                            <legend>Selected Itinerary for Supplement Points</legend>
                            <div class="row" style="max-height: 420px; overflow: auto;">
                                 <asp:GridView ID="SelectedItineraryGridView" runat="server" 
                                    autogeneratedcolumns = "false" EmptyDataText="No Records Selected"
                                    skinid = "GridViewSkin" onrowdeleting="SelectedItineraryGridView_RowDeleting" 
                                    AutoGenerateColumns="False" GridLines="None" Width="100%" >
                                    <Columns>
                                      
                                        <asp:TemplateField>
                                        <ItemTemplate>
                                        <div style="display:none;">
                                        <asp:Label ID="ItineraryIDLabel" runat="server" Text='<%#Eval("ItineraryID") %>'></asp:Label>
                                        </div>
                                       <div>
                                       
                                        <asp:Label ID="ItinearyHeadingLabel" runat="server" Text='<%#Eval("ItineraryHeading") %>' ToolTip='<%#Eval("ItineraryDetail") %>' Width="300px"  ></asp:Label>
                                       </div>
                                        </ItemTemplate>
                                       <ItemStyle Width="300px" /> 
                                        </asp:TemplateField>
                                        <asp:CommandField ButtonType="Image" DeleteText="" ShowDeleteButton="True"
                                            DeleteImageUrl="~/App_Themes/BusinessAdminDefault/Images/DeleteImg.png">
                                            <ItemStyle Width="40px" />
                                        </asp:CommandField>
                                    </Columns>
                                    <PagerStyle BorderStyle="Solid" />
                                </asp:GridView>
                            </div>
                            
                        </fieldset>
                         <div style="clear:both;"></div>
                        <fieldset style="float: left; margin-left: 15px; width: 930px;">
                        <legend>Configure Supplement Points</legend>
                        
                        <div>  
                            <div style = "width: 55%; float: left;">
                               Select The Supplement Point And  Configure It 
                            </div>
                            <div style = "width: 45%; float: left;">
                               <asp:DropDownList ID="SuppPointsDropDownList" runat="server" 
                                    AppendDataBoundItems="true" Width="350px"  AutoPostBack="true">
                               </asp:DropDownList>
                            </div>    
                        </div>
                          <div style="clear:both; height:5px;"></div>
                       <div>  
                            <div style = "width: 15%; float: left;">
                              Effective From 
                            </div>
                            <div style = "width: 34%; float: left;">
                             <asp:TextBox ID="FromDateTextBox" runat="server" Width="230px" ></asp:TextBox>
                             <ajaxToolkit:CalendarExtender ID="CalenderExtender1" runat="server" TargetControlID="FromDateTextBox" Format="dd-MMM-yyyy"></ajaxToolkit:CalendarExtender>
                            </div>  
                            <div style = "width: 15%; float: left;">
                             Upto 
                            </div>
                            <div style = "width: 34%; float: left;">
                            <asp:TextBox ID="UptoDateTextBox" runat="server" Width="230px"  ></asp:TextBox>
                            <ajaxToolkit:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="UptoDateTextBox" Format="dd-MMM-yyyy"></ajaxToolkit:CalendarExtender>
                            </div>    
                        </div>
                          <div style="clear:both; height:5px;"></div>
                        <div>  
                            <div style = "width: 15%; float: left;">
                             Cost Price
                            </div>
                            <div style = "width: 34%; float: left;">
                             <asp:TextBox ID="CostPriceTextBox" runat="server" Width="230px"  ></asp:TextBox>

                            </div>  
                            <div style = "width: 15%; float: left;">
                            Selling Price
                            </div>
                            <div style = "width: 34%; float: left;">
                            <asp:TextBox ID="SellingPriceTextBox" runat="server" Width="230px"  ></asp:TextBox>

                            </div>    
                        </div>
                    </fieldset>
                    </div>
                    <fieldset style="float: left; margin-left: 15px; width: 930px;">
                    
                        <div class="FromBodyButtonContainer">
                            <asp:Button ID="AddButton" runat="server" Text=" Add " CssClass="FromBodyButton"
                                Width="80px" OnClick="AddButton_Click" />
                            <asp:Button ID="EditButton" runat="server" Text=" Edit " CssClass="FromBodyButton"
                                Width="80px" OnClick="EditButton_Click" />
                            <asp:Button ID="SaveButton" runat="server" Text=" Save " CssClass="FromBodyButton"
                                ValidationGroup="ValidateData" Width="80px" OnClick="SaveButton_Click" />
                            <asp:Button ID="ClearButton" runat="server" Text=" Clear " CssClass="FromBodyButton"
                                Width="80px" OnClick="ClearButton_Click" />
                        </div>
                    </fieldset>
                    <fieldset style="float: left; margin-left: 15px; width: 930px;">
                        <gridUC:CustomGridView ID="ETravelCustomGridView" runat="server" Width="100%" />
                    </fieldset>
                </div>
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>
    </div>
</asp:Content>
