<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/BusinessAdmin.Master"
    AutoEventWireup="true" CodeBehind="ConfigDiscount.aspx.cs" Inherits="e_Travel.BusinessAdmin.ConfigDiscount" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <%-- <script type="text/javascript">
        $(document).ready(function () {
            $('[id$=VehicleDiscountTextBox]').keyup(function () {
                if (this.value.length > 0) { $('[id$=DiscountTextBox]').prop('disabled', true) }
                else { $('[id$=DiscountTextBox]').prop('disabled', false) } 
            })
        });
    </script>--%>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="FromBody">
        <asp:UpdatePanel runat="server" ID="UpdatePanel1">
            <ContentTemplate>
                <div class="BoxHeader">
                    Discount/Offer Configuration</div>
                <div class="BoxBody">
                    <div class="BoxContent">
                        <fieldset style="float: left; margin-right: 15px; overflow: auto; width: 515px;">
                            <legend>Select Packages to Configure Discount/Offer</legend>
                            <div>
                                 <searchGridUC:SearchCustomGridView ID="tpkSeachCustomGridView" runat="server" />
                            </div>
                        </fieldset>
                        <fieldset style="float: left; margin-right: 5px; overflow: hidden; width: 375px; height: 440px;">
                            <legend>Selected Packages for Doscount</legend>
                            <div class="row" style="max-height: 420px; overflow: auto;">
                                <asp:GridView ID="selectedtpkGridView" runat="server" 
                                    autogeneratedcolumns = "false" EmptyDataText="No Records Selected"
                                    skinid = "GridViewSkin" onrowdeleting="selectedtpkGridView_RowDeleting" 
                                    AutoGenerateColumns="False" GridLines="None">
                                    <Columns>
                                        <asp:BoundField DataField="TpkID" HeaderText="Code" >
                                            <ItemStyle Width="60px" />
                                        </asp:BoundField>
                                        <asp:BoundField DataField="TpkName" HeaderText="Package Name" >
                                            <ItemStyle Width="250px" />
                                        </asp:BoundField>
                                        <asp:CommandField ButtonType="Image" DeleteText="" ShowDeleteButton="True"
                                            DeleteImageUrl="~/App_Themes/BusinessAdminDefault/Images/DeleteImg.png">
                                            <ItemStyle Width="40px" />
                                        </asp:CommandField>
                                    </Columns>
                                    <PagerStyle BorderStyle="Solid" />
                                </asp:GridView>
                            </div>
                            
                        </fieldset>
                    </div>
                    <fieldset style="float: left; margin-left: 15px; width: 930px;">
                        <legend>Discount/Offer Details</legend>
                        <div class="row">
                            <div style = "width: 55%; float: left; padding-top: 4px;">
                                Date from which Offer/Discount is Applicable for the above selected Tour packages:
                            </div>
                            <div style = "width: 45%; float: left;">
                                <asp:TextBox ID="EffectiveDateTextBox" runat="server" ValidationGroup="ValidateData"
                                    TextMode="SingleLine" EnableViewState="False" Width="100px"></asp:TextBox>
                                <ajaxToolkit:CalendarExtender ID="StartDateCalendarExtender" runat="server" TargetControlID="EffectiveDateTextBox"
                                    Format="dd-MMM-yyyy">
                                </ajaxToolkit:CalendarExtender>
                            </div>
                        </div>
                        <div>  
                            <div style = "width: 55%; float: left;">
                                Date upto which Offer/Discount is Applicable for the above selected Tour Packages:
                            </div>
                            <div style = "width: 45%; float: left;">
                                <asp:TextBox ID="EndDateDateTextBox" runat="server" ValidationGroup="ValidateData"
                                    TextMode="SingleLine" EnableViewState="False" Width="100px"></asp:TextBox>
                                <ajaxToolkit:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="EndDateDateTextBox"
                                    Format="dd-MMM-yyyy">
                                </ajaxToolkit:CalendarExtender>
                            </div>    
                        </div>
                        <div class="row">
                            <div style = "width: 55%; float: left;">
                                Enter discount % that you want to offer for the selected Tour packages:
                            </div>
                            <div style = "width: 45%; float: left;">
                                <asp:TextBox ID="DiscountTextBox" runat="server" width = "100px"></asp:TextBox>
                            </div>    
                        
                            <%--<asp:Panel ID="Panel1" runat="server">
                                <div>
                                    <label for="VehicleDiscountTextBox">
                                        Vehicle</label>
                                    <asp:TextBox ID="VehicleDiscountTextBox" runat="server" OnTextChanged="VehicleDiscountTextBox_TextChanged"
                                        AutoPostBack="true"></asp:TextBox>
                                </div>
                                <br />
                                <div>
                                    <label for="AccTextBox">
                                        Accomodation</label>
                                    <asp:TextBox ID="AccTextBox" runat="server" OnTextChanged="AccTextBox_TextChanged"
                                        AutoPostBack="true"></asp:TextBox>
                                </div>
                                <br />
                                <div>
                                    <label for="DiscountTextBox">
                                        Discount</label>
                                    <asp:TextBox ID="DiscountTextBox" runat="server"></asp:TextBox>
                                </div>
                            </asp:Panel>--%>
                        </div>
                        <div class="row">
                            <div style = "width: 100%; float: left;">
                                Discount Description (150 Chars Max) - Note: The description you are entering will be displayed to the end user.
                            </div>
                            <div style = "width: 100%; float: left;">
                                <asp:TextBox ID="DiscountDisTextBox" runat="server" TextMode="MultiLine" EnableViewState="False" Width="915px"></asp:TextBox>
                            </div>    

                            <label for="DiscountDisTextBox">
                                </label>
                            
                        </div>
                    </fieldset>
                    <fieldset style="float: left; margin-left: 15px; width: 930px;">
                        <div class="FromBodyButtonContainer">
                            <asp:Button ID="AddButton" runat="server" Text=" Add " CssClass="FromBodyButton"
                                Width="80px" OnClick="AddButton_Click" />
                            <asp:Button ID="EditButton" runat="server" Text=" Edit " CssClass="FromBodyButton"
                                Width="80px" OnClick="EditButton_Click" />
                            <asp:Button ID="SaveButton" runat="server" Text=" Save " CssClass="FromBodyButton"
                                ValidationGroup="ValidateData" Width="80px" OnClick="SaveButton_Click" />
                            <asp:Button ID="ClearButton" runat="server" Text=" Clear " CssClass="FromBodyButton"
                                Width="80px" OnClick="ClearButton_Click" />
                        </div>
                    </fieldset>
                    <fieldset style="float: left; margin-left: 15px; width: 930px;">
                        <gridUC:CustomGridView ID="ETravelCustomGridView" runat="server" Width="100%" />
                    </fieldset>
                </div>
                </div>
            </ContentTemplate>
        </asp:UpdatePanel>
    </div>
</asp:Content>
